#!/usr/bin/env bash
# shellcheck disable=SC2086
# display information about subdomains

display_subdomain_info() {
  local domain=$1
  local subdomain=$2
  if [ -z "$subdomain" ]; then
    echo "Information for subdomains www, lb-01, web-01, web-02:"
    for sub in www lb-01 web-01 web-02; do
      subdomain_info=$(dig +short "$sub.$domain" | awk '{print "The subdomain "$1" is a A record and points to "$2}')
      echo "$subdomain_info"
    done
  else
    subdomain_info=$(dig +short "$subdomain.$domain" | awk '{print "The subdomain "$1" is a A record and points to "$2}')
    echo "$subdomain_info"
  fi
}

display_subdomain_info "$1" "$2"
